"""Fetch a small sample of SFHQ-T2I synthetic faces for the chapter demos.

SFHQ-T2I (github.com/SelfishGene/SFHQ-T2I-dataset) is fully synthetic — faces
generated by Flux / SDXL / DALL-E 3, no real people.

Distribution is via Kaggle, so this needs a free Kaggle API token
(~/.kaggle/kaggle.json — see https://www.kaggle.com/docs/api). To keep the
download small we list the dataset's files and pull only N individual images
rather than the full multi-GB archive.

Run:
    uv run python fetch_faces.py --n 40 --out faces
"""

import argparse
import random
from pathlib import Path

KAGGLE_SLUG = "selfishgene/sfhq-t2i-synthetic-faces-from-text-2-image-models"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png"}


def main() -> None:
    """Sample synthetic faces from the dataset via Kaggle."""
    ap = argparse.ArgumentParser(description="Sample N SFHQ-T2I faces via Kaggle.")
    ap.add_argument("--n", type=int, default=40, help="how many faces to fetch")
    ap.add_argument("--out", type=Path, default=Path("faces"), help="output dir")
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    # Import here so the module loads even without kaggle installed/configured.
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()  # reads ~/.kaggle/kaggle.json

    # List files and keep only images. If the dataset is one big archive rather
    # than individual files, per-file download won't apply — see the note below.
    listing = api.dataset_list_files(KAGGLE_SLUG).files
    image_files = [
        f.name for f in listing if Path(f.name).suffix.lower() in IMAGE_SUFFIXES
    ]
    if not image_files:
        raise SystemExit(
            "No individually-listed image files — the dataset is likely a single "
            "archive/HDF5. Download it once with `kaggle datasets download "
            f"{KAGGLE_SLUG}`, unzip, then point --out at the extracted images."
        )

    random.seed(args.seed)
    sample = random.sample(image_files, min(args.n, len(image_files)))
    for i, name in enumerate(sample):
        # Download each file individually into --out (unzips single-file zips).
        api.dataset_download_file(KAGGLE_SLUG, name, path=str(args.out), force=False)
        print(f"[{i + 1}/{len(sample)}] {name}")

    print(f"Done — {len(sample)} faces under {args.out}")


if __name__ == "__main__":
    main()
